# Generated by Django 4.2.3 on 2023-07-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocMed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('by', models.CharField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('by', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('for_Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocMed.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='for_Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocMed.post'),
        ),
    ]
