# Generated by Django 4.2.3 on 2023-07-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocMed', '0006_alter_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocMed.account'),
        ),
    ]
