# Generated by Django 4.2.3 on 2023-07-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocMed', '0007_alter_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocMed.account'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocMed.account'),
        ),
    ]
